# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 7

# Commands to be run before your environment runs.
before_script:
  - composer self-update

matrix:
  allow_failures:
    - php: 7
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always
